export const FETCHING_PRODUCTS = 'FETCHING_PRODUCTS';
export const FETCHING_PRODUCTS_SUCCESSFULLY = 'FETCHING_PRODUCTS_SUCCESSFULLY';
export const FETCHING_PRODUCTS_ERROR = 'FETCHING_PRODUCTS_ERROR';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESSFULLY = 'ADD_PRODUCT_SUCCESSFULLY';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';
